name:                hasuke
version:             0.1.0.0
github:              "tkuriyama/hasuke"
license:             BSD3
author:              "Taro Kuriyama"
maintainer:          "taro@tarokuriyama.com"
copyright:           "2020 Taro Kuriyama"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         https://github.com/tkuriyama/hasuke

dependencies:
  - base >= 4.7 && < 5
  - text
  - aeson
  - Euterpea

library:
  source-dirs:
    - src
  default-extensions:
    - OverloadedStrings
    - DeriveGeneric
    - ExtendedDefaultRules
  dependencies:
    - lucid

executables:
  hasuke-make:
    main:                Main.hs
    source-dirs:         make/
    default-extensions:
      - OverloadedStrings
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - hasuke
      - filepath

tests:
  hasuke-test:
    main:                Spec.hs
    source-dirs:         test
    default-extensions:
      - OverloadedStrings
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
    - hasuke
